#!/usr/bin/perl -w
use strict;

if ( ! open SAMPLE, "sample") {
die "How did you get logged in? ($!)";
}
my $lines;

while(<SAMPLE>) {
	chomp;
	$lines .= "$_\n";
}

$lines = "success\n" if 1 eq 1;

$lines =~ s#^.*/##s;
print $lines;

for ($_ = "bedrock"; s/(.)//; ) { # loops while the s/// is successful
print "One character is: $1\n";
}

my @words = qw{ fred barney pebbles dino wilma betty };
my $errors = 0;
foreach (@words) {
## redo comes here ##
print "Type the word '$_': ";
chomp(my $try = <STDIN>);
if ($try ne $_) {
print "Sorry - That's not right.\n\n";
$errors++;
redo; # jump back up to the top of the loop
}
}
print "You've completed the test, with $errors errors.\n";
