#!/usr/bin/perl -w
use strict;
use 5.010;

say 'Welcome to Hash Sample.';

my %hash = (
	'rodrigo' => [ 28, 'Male', 'Taguig'],
	'adolfo' => [ 29, 'Male', 'Makati'],
	'Delena' => [ 30, 'Female', 'Pateros'],
	);

print $hash{'rodrigo'}->[1];
