#!/usr/bin/perl -w
use strict;
my ($n,$root);

{
	print "Please enter a number: ";
	chomp($n=<STDIN>);
	$root = sqrt $n;
	print "The square root of $n is $root.\n";
}


unless (defined $root) {
	print "The value is undef.\n";
}

#if ( ! defined $root) {
#	print "The value is undef.\n";
elsif ( $root =~ /^-?\d+\.?$/ ) {
	print "The square root of $n is integer: $root.";
}elsif ( $root =~ /^-?\d*\.\d+?$/ ) {
	printf "The square root of $n is floating %0.2f", $root;
}else {
	print 'Please try again.';
}

foreach (1..10) {
print "\nIteration number $_.\n\n";
print "Please choose: last, next, redo, or none of the above? ";
chomp(my $choice = <STDIN>);
print "\n";
last if $choice =~ /last/i;
next if $choice =~ /next/i;
redo if $choice =~ /redo/i;
print "That wasn't any of the choices... onward!\n\n";
}
print "That's all, folks!\n";
