#!/usr/bin/perl -w
use strict;

use 5.010;

greet( 'Fred' );
greet( 'Barney' );
greet( "Wilma" );
greet( "Betty" );

sub greet {
state $last_person;
my $name = shift;
print "Hi $name! ";
if( defined $last_person ) {
print "I've seen: $last_person\n";
}
else {
print "You are the first one here!\n";
}
$last_person = $name;
}

## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.