#!/usr/bin/perl -w
use strict;

my %hash = (
	  d => 1,
	 'a' => 3,
	 'b' => 5,
	 'c' => 10,
	);

while ( my ($key, $value) = each %hash ) {
print "$key => $value\n";
}

foreach my $key (sort keys %hash) {
my $value = $hash{$key};
print "$key => $value\n";
}
