#!/usr/bin/perl -w
use strict;
use 5.010;

my ($in_fh, $out_fh);

my $in = $ARGV[0];
if (! defined $in) {
die "Usage: $0 filename";
}
my $out = $in;
$out =~ s/(\.\w+)?$/.out/;

if (! open $in_fh, '<', $in ) {
die "Can't open '$in': $!";
}
if (! open $out_fh, '>', $out ) {
die "Can't write '$out': $!";
}
while (<$in_fh>) {
s/Manfred/Larry/gi;
s/Fred(.*)wilma/Wilma$1Fred/gi;
print $out_fh $_;
}


## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.