#!/usr/bin/perl -w
use strict;
chomp(my $date = `date`);
$^I = ".bak";
while (<>) {
s/^Author:.*/Author: Randal L. Schwartz/;
s/^Phone:.*\n//;
s/^Date:.*/Date: $date/;
s/^Version:.*/Version: 2.2/;
print;
}
## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.
## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.