#!/usr/bin/perl -w
use strict;
use 5.010;

$_ = "ab-...c";
if (/(.)\1/) { # matches 'bb'
print "It matched same character next to itself!\n";
}

$_ = "yabba dabba doo";
if (/y(....) d\1/) {
print "It matched the same after y and d!\n";
}
$_ = "yabba dabba doo";
if (/y(.)(.)\2\1/) { # matches 'abba'
print "It matched after the y!\n";
}

## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.
## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.