#!/usr/bin/perl -w
use strict;
use 5.010;

my $ip = '192.168.56.250/24';

if ( $ip =~ m/(\d+)(.)(\d+)(.)(\d+)(.)(\d+)\/(\d+)/ ) {
	print " $1.$3.$5.$7 ";
	my $subnet = $8;
	if ($8 =~ m/(\d+)/) {
		print "success";
	}
}
