#!/usr/bin/perl -w
use strict;
use 5.010;

my ($ip, $sub_mask, $octet, $num, $m, $d, $total_bits, $bit, $last, $min, $max);
my ($frst, $scnd, $thrd, $frth); 
say "Input the Network address (Host or Network)";
$ip =<STDIN>;
$m =  '(\d+)\.';
$d = '(\d+)';
if ($ip =~ m/$m$m$m$d\/$d/) {
	 $num = $5 / 8;
	($frst, $scnd, $thrd, $frth) = ($1, $2, $3, $4);
	 if ( $num >= 8 || $num <= 32 ) { 
		if ( $num =~ /$m$d/ ) {
			if ( $1 > 3){ $octet = $num;} else{ $octet = $1;}
			if ( $2 == 875 ) { octet_($bit = 2);}
			if ( $2 == 75 ) { octet_($bit = 4);}
			if ( $2 == 625 ) { octet_($bit = 8);}
			if ( $2 == 5 ) { octet_($bit = 16);}
			if ( $2 == 375 ) { octet_($bit = 32);}
                        if ( $2 == 25 ) { octet_($bit = 64);}
                        if ( $2 == 125 ) { octet_($bit = 128);}
		}elsif ( $num =~ /$d/ ) {
			$octet = $1;
			octet_($bit = 0);
		}

		print "$min $max $sub_mask";
	}
	if ($5<8 || $5>32) {	print "Your slash is less than eight or greater than 32, please try again.";	}

}elsif ($ip =~ m/$m$m$m$d/) {
	say "Input the Subnet Mask (e.g. 255.255.255.0)";
	$sub_mask =<STDIN>;
}
else {
	print "Error";
}


sub octet_ {
if ($octet == 1) { 
	$last = total($_);
	$sub_mask = "$last.255.0.0";}
elsif ($octet == 2) {
	$last = total($_);
       	$sub_mask = "255.$last.0.0";}
elsif ($octet == 3) { 
	$last = total($_);
	$min = $scnd;
        while ($scnd < $bit){
                $scnd++;
        }
        $max = $scnd;
	$sub_mask = "255.255.$last.0";}
elsif ($octet > 3) {
	$last = total($_);
	$sub_mask = "255.255.255.$last";}
else { $sub_mask = "";}
}
sub total {
	if ($bit == 0) {
		$total_bits = 0;
	} else {
	        $total_bits = 256 - $bit;
	}
}

