#!/usr/bin/perl -w
use strict;
use 5.010;

my ($ip, $sub_mask, $octet, $num, $m, $d, $bit, $last_mask, $min, $max, $new, $broadcast, $network);
my ($frst, $scnd, $thrd, $frth, $first, $last, $first_ip, $last_ip, $net, $bcast, $bit_ad); 
say "Input the Network address (Host or Network)";
$ip =<STDIN>;
$m =  '(\d+)\.';
$d = '(\d+)';
if ($ip =~ m/$m$m$m$d\/$d/) {
	 $num = $5 / 8;
	($frst, $scnd, $thrd, $frth) = ($1, $2, $3, $4);
	 if ( $num <= 32 ) { 
		if ( $num =~ /$m$d/ ) {
			if ( $1 > 3){ $octet = $num;} else{ $octet = $1;}
			if ( $2 == 875 ) { octet_(2);}
			if ( $2 == 75 ) { octet_(4);}
			if ( $2 == 625 ) { octet_(8);}
			if ( $2 == 5 ) { octet_(16);}
			if ( $2 == 375 ) { octet_(32);}
                        if ( $2 == 25 ) { octet_(64);}
                        if ( $2 == 125 ) { octet_(128);}
		}elsif ( $num =~ /$d/ ) {
			$octet = $1;
			octet_($bit = 0);
		}
		print "Network: $network\nBroadcast: $broadcast\nFirst usable IP: $first_ip\nLast usable IP: $last_ip\nSubnet Mask: $sub_mask\n";
	}
	if ($5<8 || $5>32) {	print "Your slash is less than eight or greater than 32, please try again.";	}

}elsif ($ip =~ m/$m$m$m$d/) {
	say "Input the Subnet Mask (e.g. 255.255.255.0)";
	$sub_mask =<STDIN>;
}
else {
	print "Error";
}


sub octet_ {
	$bit=$_[0];
if ($octet == 0) {
	total($frst,$bit);
        $first_ip = "$net.0.0.1";
        $last_ip = "$bcast.255.255.254";
        $broadcast = "$bcast.255.255.255";
	$sub_mask = "$last_mask.0.0.0";
        $network = "$net.0.0.0";
}
elsif ($octet == 1) { 
	total($scnd,$bit);
	$first_ip = "$frst.$net.0.1";
	$last_ip = "$frst.255.255.$last";
	$broadcast = "$frst.$bcast.255.255";
	$sub_mask = "255.$last_mask.0.0";
	$network = "$frst.$net.0.0";
}
elsif ($octet == 2) {
	total($thrd,$bit);
	$first_ip = "$frst.$scnd.$first.1";
	$last_ip = "$frst.$scnd.$bcast.254";
	$broadcast = "$frst.$scnd.$bcast.255";
	$sub_mask = "255.255.$last_mask.0";
	$network = "$frst.$scnd.$net.0";
}
elsif ($octet == 3) { 
	total($frth,$bit);
	$first_ip = "$frst.$scnd.$thrd.$first";
	$last_ip = "$frst.$scnd.$thrd.$last";
	$broadcast = "$frst.$scnd.$thrd.$bcast";
	$sub_mask = "255.255.255.$last_mask";
	$network = "$frst.$scnd.$thrd.$net";
}
else { $sub_mask = "";}
}
sub total {
		$bit_ad = $bit;
                if ($_[0] < $bit) {
                        $net = $bit-$bit_ad;
                        $bcast=$bit_ad-1;
                        $last_ip=$bit_ad-2;
                        $first_ip=$net+1;
                }elsif ($_[0] % $bit == 0 || $bit % $_[0] == 0) {
			$net = $_[0];
			$first = $net+1;
			$bcast = $_[0]+$bit-1;
			$last = $bcast-1;
		}else {
                        while($_[0] > $bit) {
                                $bit+=$bit_ad;
                                $last=$bit-2;
                                $net=$bit-$bit_ad;
                                $first=$net+1;
                                $bcast=$bit-1;
                        }
                }
		$last_mask = 256 - $bit;
}


## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.
