#!/usr/bin/perl -w
use strict;
use 5.010;

my ($ip, $sub_mask, $octet, $num, $m, $d, $bit, $last_mask, $min, $max, $new);
my ($frst, $scnd, $thrd, $frth, $first, $last, $first_ip, $last_ip, $net, $bcast, $bit_ad); 
say "Input the Network address (Host or Network)";
$ip =<STDIN>;
$m =  '(\d+)\.';
$d = '(\d+)';
if ($ip =~ m/$m$m$m$d\/$d/) {
	 $num = $5 / 8;
	($frst, $scnd, $thrd, $frth) = ($1, $2, $3, $4);
	 if ( $num >= 8 || $num <= 32 ) { 
		if ( $num =~ /$m$d/ ) {
			if ( $1 > 3){ $octet = $num;} else{ $octet = $1;}
			if ( $2 == 875 ) { octet_(2);}
			if ( $2 == 75 ) { octet_(4);}
			if ( $2 == 625 ) { octet_(8);}
			if ( $2 == 5 ) { octet_(16);}
			if ( $2 == 375 ) { octet_(32);}
                        if ( $2 == 25 ) { octet_(64);}
                        if ( $2 == 125 ) { octet_(128);}
		}elsif ( $num =~ /$d/ ) {
			$octet = $1;
			octet_($bit = 0);
		}

		#print "$min $max $sub_mask";
	}
	if ($5<8 || $5>32) {	print "Your slash is less than eight or greater than 32, please try again.";	}

}elsif ($ip =~ m/$m$m$m$d/) {
	say "Input the Subnet Mask (e.g. 255.255.255.0)";
	$sub_mask =<STDIN>;
}
else {
	print "Error";
}


sub octet_ {
	$bit=$_[0];
if ($octet == 1) { 
	total($scnd,$bit);
	$sub_mask = "255.$last.0.0";
}
elsif ($octet == 2) {
	total($thrd,$bit);
	$sub_mask = "255.255.$last.0";

}
elsif ($octet == 3) { 
	total($frth,$bit);
	$sub_mask = "255.255.255.$last";
}
else { $sub_mask = "";}
}
sub total {
	if ($bit == 0) {
		$total_bits = 0;
	} else {
		$bit_ad = $bit;
                if ($_[0] < $bit) {
                        $net = $bit-$bit_ad;
                        $bcast=$bit_ad-1;
                        $last_ip=$bit_ad-2;
                        $first_ip=$net+1;
                }else {
                        while($_[0] > $bit) {
                                $bit+=$bit_ad;
                                $last=$bit-2;
                                $net=$bit-$bit_ad;
                                $first=$net+1;
                                $bcast=$bit-1;
                        }
                }
		#print "Net: $net, Broadcast: $bcast, First and last usable IP: $first_ip and $last_ip\n";
		$last_mask = 256 - $bit;
	}
}


## Copyright (C) 2017 by Rodrigo D. Adolfo Jr.
